'use strict';

//  This is the same way as WPT categorize the events
// https://github.com/WPO-Foundation/webpagetest/blob/master/www/breakdownTimeline.php#L56
// And we been doing the same with
// https://github.com/wikimedia/wpt-reporter/blob/master/lib/cpuTime.js#L10-L13
module.exports = {
  EvaluateScript: 'Scripting',
  'v8.compile': 'Scripting',
  FunctionCall: 'Scripting',
  GCEvent: 'Scripting',
  TimerFire: 'Scripting',
  EventDispatch: 'Scripting',
  TimerInstall: 'Scripting',
  TimerRemove: 'Scripting',
  XHRLoad: 'Scripting',
  XHRReadyStateChange: 'Scripting',
  MinorGC: 'Scripting',
  MajorGC: 'Scripting',
  BlinkGCMarking: 'Scripting',
  FireAnimationFrame: 'Scripting',
  'ThreadState::completeSweep': 'Scripting',
  'Heap::collectGarbage': 'Scripting',
  'ThreadState::performIdleLazySweep': 'Scripting',
  Layout: 'Layout',
  UpdateLayoutTree: 'Layout',
  RecalculateStyles: 'Layout',
  ParseAuthorStyleSheet: 'Layout',
  ScheduleStyleRecalculation: 'Layout',
  InvalidateLayout: 'Layout',
  Paint: 'Painting',
  DecodeImage: 'Painting',
  'Decode Image': 'Painting',
  ResizeImage: 'Painting',
  CompositeLayers: 'Painting',
  Rasterize: 'Painting',
  PaintImage: 'Painting',
  PaintSetup: 'Painting',
  ImageDecodeTask: 'Painting',
  GPUTask: 'Painting',
  SetLayerTreeId: 'Painting',
  layerId: 'Painting',
  UpdateLayer: 'Painting',
  UpdateLayerTree: 'Painting',
  'Draw LazyPixelRef': 'Painting',
  'Decode LazyPixelRef': 'Painting',
  ParseHTML: 'Loading',
  ResourceReceivedData: 'Loading',
  ResourceReceiveResponse: 'Loading',
  ResourceSendRequest: 'Loading',
  ResourceFinish: 'Loading',
  CommitLoad: 'Loading',
  Idle: 'Idle'
};
